### ISSUE TITLE
delayed by one candle

### ISSUE THREAD

**Issue by minhyeong112** [goncaloe/nnfx-backtest#10]
Hello,

![ex1](https://user-images.githubusercontent.com/104501046/165506243-60da5c82-ee77-48c8-a701-a2ca27d387d9.PNG)
![ex2](https://user-images.githubusercontent.com/104501046/165506245-4eb6ec15-1212-4036-8239-1d2320f0949b.PNG)
![ex3](https://user-images.githubusercontent.com/104501046/165506246-b173842f-199d-407f-95d4-6a5f0ab5ac1b.PNG)

I might be seeing it the wrong way, but I believe that the trade entries are delayed by one candle.  

In the attached pictures, I put a RED circle where I think the trade should enter (first open after signal).  But, every single time, the entry seems to be delayed by a day (circled in BLUE).  Can you please help me understand/fix this?

**Comment by goncaloe** [comment]
The reason for this was explained in last section of readme:
The strategy tester in "Open prices only" model check signals on every new candle at 0:00. At this point, we can't use the close price for it is not yet formed. Because this the EA use the close of previous candle to check signals. When there are entry signals (previous close), the order will be open with current Bid/Ask price, which does not correspond to the closing price of the previous candle.
